version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
 
  AfterInstall:
    - location: /home/ubuntu/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/scripts/start_app.sh
      timeout: 20
      runas: ubuntu
  ApplicationStop:
    - location: /home/ubuntu/scripts/stop_app.sh
      timeout: 20
      runas: ubuntu
