version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/
 
permissions:
  - object: install_dependencies.sh
    owner: root
    mode: 755
    type:
      - file
  - object: start_app.sh
    owner: root
    mode: 755
    type:
      - file
  - object: stop_app.sh
    owner: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
  
