version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/
 
permissions:
  - object: /home/ec2-user/scripts/install_dependencies.sh
    owner: root
    mode: 755
    type:
      - file
  - object: /home/ec2-user/scripts/start_app.sh
    owner: root
    mode: 755
    type:
      - file
  - object: /home/ec2-user/scripts/stop_app.sh
    owner: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_ap.sh
      timeout: 300
      runas: root
