version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
 BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: install_dependencies.sh.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_app.sh
      timeout: 20
      runas: ubuntu
  ApplicationStop:
    - location: stop_app.sh
      timeout: 20
      runas: ubuntu
