version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
 BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: install_dependencies.sh.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_app.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: stop_app.sh
      timeout: 20
      runas: ec2-user
